#!/bin/bash
for MACHINE in $(docker-machine ls --format '{{.Name}}')
do 
	docker-machine ssh $MACHINE 'sudo -i s3cmd get --force s3://modelstorage/dynamic.rds /models/dynamic.rds' 
done

echo 'complete'
